# Generated by Django 5.0 on 2023-12-30 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_like_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('reminder', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_completed', models.BooleanField()),
                ('goal', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.goal')),
            ],
        ),
    ]
