# Generated by Django 5.0 on 2023-12-30 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.goal'),
        ),
    ]
