# Generated by Django 5.0 on 2024-01-06 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_added_related_name_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='start_date',
        ),
        migrations.AddField(
            model_name='diary',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
