# Generated by Django 5.0 on 2024-01-09 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='color',
            field=models.CharField(default='white', max_length=25),
        ),
        migrations.AddField(
            model_name='diary',
            name='emoji',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
