# Generated by Django 5.0 on 2024-01-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
    ]
