# Generated by Django 5.0 on 2024-01-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_profile_follower_count_profile_following_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following_count',
        ),
    ]
