# Generated by Django 5.0 on 2024-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_profile_follower_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
