# Generated by Django 5.0 on 2024-01-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_profile_username_alter_user_kakao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='reminder',
            field=models.DateTimeField(null=True),
        ),
    ]
