# Generated by Django 5.0 on 2024-01-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_todo_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
