# Generated by Django 5.0 on 2024-01-19 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='emoji',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
