# Generated by Django 5.0 on 2024-01-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_comment_content_type_alter_comment_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
