# Generated by Django 5.0 on 2024-01-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_todo_reminder'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
