# Generated by Django 5.0 on 2024-01-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_user_kakao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='emoji',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='like',
            name='emoji',
            field=models.CharField(max_length=64),
        ),
    ]
