# Generated by Django 5.0 on 2024-01-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_todo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='color',
            field=models.CharField(default='blue', max_length=25),
        ),
        migrations.AlterField(
            model_name='goal',
            name='color',
            field=models.CharField(default='blue', max_length=25),
        ),
    ]
