# Generated by Django 5.0 on 2024-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_diary_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='reminder',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
